version: "3.8"

services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    restart: unless-stopped
#    ports:
#      - "8000:8000/tcp"
    command: ["run", "-c", "/etc/v2ray/config.json"]
    volumes:
      - ./config.json:/etc/v2ray/config.json:ro
      - ./logs:/var/log/v2ray
    networks: ["edge"]

networks:
  edge:
    external: true
